---
date: "2019-11-03T00:00:00+01:00"
draft: false
linktitle:
menu:
  example:
    parent: 
    weight: 4
title: Data challenge with R
toc: 
type: docs
weight: 4
---

This course is designed to give you an appreciation of R programming as a tool for data exploration. It focuses on packages that will help you do exploratory data analysis, visualisation and communication in a dynamic and reproducible manner.

#### If you would like to:

- Discover how to find and access data and prepare it for exploration and visualistion
- Learn to explore, visualize, and analyse data in a dynamic and reproducible manner
- Gain experience in data wrangling, exploratory data analysis and data visualisation, and effective communication of results
- Work on case studies inspired by real problems and based on open data

#### then this course is for you! 😀


{{% callout note %}}
This course is available at 👉 <https://datachallengewithr.rbind.io/>
{{% /callout %}}

---
This workshop is a part of The Autumn Data School program organised as a part of the [Open Data - Open Opportunities](https://www.rs.undp.org/content/serbia/en/home/projects/opendata.html) project.

You can download the Autumn Data School program from [here 👇](https://www.rs.undp.org/content/dam/serbia/undp_rs_Program%20Radionice_Open%20Data-1.pdf)

The workshop has been delivered in partnership with [UNDP Serbia](http://www.rs.undp.org)
