---
date: "2020-11-20T00:00:00+01:00"
draft: false
linktitle:
menu:
  example:
    parent: 
    weight: 1
title: Learn to access, organise, analyse and argue with data using R
toc: 
type: docs
weight: 1
---

The ever emerging Internet of Things (IoT) produces vast amounts of data that can be analysed to gain useful insights into trends. The R language is widely used by statisticians for data analysis, and the popularity of R programming has increased greatly in the recent years.

In this workshop we teach you to ‘speak data using R’ by taking a step by step approach, starting by explaining core programming principles of the R programming language, to importing data and employing basic wrangling techniques and the grammar of graphics’ philosophy. This will enable you to produce compelling visualisations that can ultimately illustrate useful insights from your data.

Through a series of demonstrations and hands on exercises you will learn some of the fundamental concepts of R and you will get to know how to use its tools in a typical data science project. We will introduce you to graphical and numerical techniques for exploring the information concealed within a dataset. After we develop an understanding of our data we will use R’s reproducible approach in telling our data story by creating R-Markdown documents.

At the end of the workshop, participants will be able to:

- Import data from different sources into the R environment
- Carry out basic data pre-processing & wrangling
- Learn to distinguish the most appropriate visualisations to be used for any given data challenge
- Build advanced visualisations: graphs and maps
- Gain proficiency in data pre-processing, data wrangling and visualisation in R by putting acquired knowledge into application, adopting a reproducible approach through the creation of RMarkdown documents

{{% callout note %}}
This course is available at 👉 <https://introtor.netlify.app/>
{{% /callout %}}

👉 Go to the following GitHub repo to download the material: https://github.com/TanjaKec/ASDA

---

This workshop has been delivered for [ASDA](https://www.asda.com/) data development training.

The workshop has been delivered in partnership with [GEOLYTIX](https://geolytix.co.uk/).
