---
date: "2020-07-05T00:00:00+01:00"
draft: false
linktitle:
menu:
  example:
    parent: 
    weight: 2
title: Build a website with blogdown in R
toc: 
type: docs
weight: 2
---

The workshop provides a practical guide for crateing websites using the [`blogdown`](https://cran.r-project.org/web/packages/blogdown/blogdown.pdf) package in R that allows you to create websites from [R Markdown](https://cran.r-project.org/web/packages/rmarkdown/rmarkdown.pdf) files using [Hugo](https://gohugo.io/), an open-source static site generator written in [Go](https://golang.org/). In this workshop you learn how to create dynamic R Markdown documents to build static websites allowing you to use R code to render the results of your analysis. The `blogdown` through the use of R Markdown allows technical writing allowing you to add graphs, tables, [LaTeX](https://www.latex-project.org/) equations, theorems, citations, and references. This makes `blogdown` an perfect tool for designing websites to communicate your R data story telling or just awesome general-purpose websites. After you create your awesome website using the `blogdown` and Hugo template you can push it onto your [GitHub](https://github.com/) and deploy on [Netlify](https://www.netlify.com/) all free of charge.  

Objectives:

-	Apply [HUGO theme](https://themes.gohugo.io/) to create a website using the `blogdown` 
-	Personalise the website
-	Deploy site from your computer to the Internet
-	Use GitHub for version control
-	Use Netlify for continuous deployment
-	Updating your website: serving site, push to GitHub, deploy

{{% callout note %}}
This course is available at 👉 <https://websiteinr.netlify.app/>
{{% /callout %}}

👉 Go to the following GitHub repo to download the material: https://github.com/TanjaKec/eRum2020
 and follow the steps given in the Xaringan presentation available from 👉 [here](https://erum2020.netlify.app/)
 
```{r embed2, out.extra='style="border: none;"', fig.cap="Xaringan presentation", echo = FALSE}
knitr::include_url('https://erum2020.netlify.app/#1')
```

---

The workshop has been delivered at [eRum!2020 - European R Users Meeting](https://2020.erum.io/)
