---
title: "Curriculum Vitae"
author: "Tatjana Kecojevic"
date: "https://tatjanakeco.rbind.io"
output: pdf_document
---


### EDUCATION
- University of Manchester, UK; 2011. Ph.D., Statistics
- University of Central Lancashire, UK; 2003. PGCert. Postgraduate Certificate in Teaching and Learning in Higher Education
- University of Belgrade, Serbia; 1998. BSc, Information Systems Engineering

### POSITIONS

**September 2020 - present**

-  **Board Member**

   [**DS Serbia**](http://www.datascience.rs/)
    
    Responsibilities include:
    
    * Co-leader of Gender Empowerment Initiative
    * Programme Adviser


**September 2019 - present** 

- **Founder and Executive Director** 

  [**SisterAnalyst NGO**](https://sisteranalyst.org)
    
    Responsibilities include:
    
    * Leading and managing the organization
    * Organising and developing a diverse range of DS training strategies
    * Engaging the external community
    

**February 2019 - present**

- **Member of the Organisation Committee** 
  
  [**DS Europe Conference**](https://datasciconference.com/)
    
    Responsibilities include:
    
    * Co-organiser of the conference programme
    

**December 2018 - present**

- **Ambassador**
  
  [**WiDS**](https://www.widsconference.org/)
    
    Responsibilities include:
    
    * Organiser and coordinator of the WiDS Subotica events


 
**July 2018 - present**

- **Core Team Member**
  
  [**R Forwards**](https://forwards.github.io/)

    Responsibilities include:

    * ‘Surveys’ team leader


**May 2017 - September 2019**

- **Co-Founder**
  
  [**DataTeka**](https://www.datateka.com)

    Responsibilities include:
    * Creating DS course materials and teaching aids that support content delivery and skills assessment
    * Carrying out statistical analysis and working with clients to interpret the results and how they impact their business
    * Engaging the youth community through the [klikR](http://klikr.rbind.io) initiative
    
**November 2016 - present**  

- **Founder of Manchester Chapter**
  
  [**R-Ladies**](https://rladies.org)

    Responsibilities include:
    * Founder and co-organiser of Manchester, Belgrade and Novi Sad Chapters
    
**September 2004 - September 2017**

- **Senior Lecturer in Quantitative Modelling**
  
  [**University of Central Lancashire**](https://www.uclan.ac.uk)

    Responsibilities include:
    * Course Leader for part-time undergraduate Business Administration Business Studies, BA(Hons)
    * Business, Arts, Humanities and Social Sciences (BAHSS) research ethics committee lead reviewer
    * Athena SWAN - Data Analyst for The College of Business, Law and Social Sciences 

**November 2000 - September 2004**

- **Lecturer in Quantitative Modelling**
  
  [**University of Central Lancashire**](https://www.uclan.ac.uk)

    Responsibilities include:
    * Teaching and developing of undergraduate and postgraduate courses
    * Participating in research teams and other collaborative research initiatives
    * Personal tutoring to 1st year undergraduate program students and placement visits
    *	Developing and delivering data analysis course training for university staff members
    *	Participating in the University’s various outreach activities


### PROJECTS

- COVID-19 SR Visualisation in R, March 2020 - present; a data analysis report concerning the visualisation of the COVID-19 virus within the Republic of Serbia
- RToolbox: a winning project at the 2nd Media Innovation Lab, November 2019 - June 2020; in partnership
with InterNews and USAID, a platform with teaching and learning material for statistical computing and visualisation, that could enhance data analysis and the reporting process for data journalism
- Mentor on the project “Data and Practice”, November 2018 - March 2019; in collaboration with the Institute for Public Health of Serbia “Dr Milan Jovanovic Batut” and UNDP Serbia
- Machine Learning Life Cycle for the problem of shipper-carrier pricing, June-September 2018; in partnership with Vibe Network, Belgrade
- Design and development of web application teaching tools for Statistics using R and Shiny, May-June 2017 
- Design and development of a Vernacular Eco Index (VEI) Shiny Dashboard: data mapping and visualisation, 2016 - 2017; in collaboration with Manchester School of Architecture
- Study on a cluster of alternative healing techniques for chronic rheumatic disease, 2013 - 2017; in collaboration with Wrightington, Wigan and Leigh NHS Foundation Trust
- Developing an assessment tool through resilient vernacular technologies for the development of European regions, 2013 - 2016; in collaboration with Manchester School of Architecture
- Assessment of clinical effectiveness of adjunctive homeopathic treatment for patients with Rheumatoid Arthritis, 2012 - date; in collaboration with Wrightington, Wigan and Leigh NHS Foundation Trust 
- The Evolution of the Boka Kotorska as a Sustainable Urban Ecological Entity, 2012 - 2013; in collaboration with School of Art, Design and Performance, UCLan
- Constructing The Reference Growth Charts for Saudi Arabian Children and Adolescents, 2006 - 2011; in collaboration with King Saud University, Riyadh
- Antagonistic relationships between fungi and nematodes, February-July 2011; in collaboration with Institute for Plant Protection and Environment, Belgrade
- Comparisons of growth and adiposity of children with atopic dermatitis with the UK population values, 2005; in collaboration with Academic Unit of Child Health, Booth Hall Children's Hospital, University of Manchester
- Analysis of suicides using methods of multivariate statistics, 1998; in collaboration with the Faculty of Organizational Science, University of Belgrade  

  #### Key functions performed:
    * Provide statistical expertise in the design of research projecst, focusing on the main issues such as clarification of the research objectives, hypotheses and basic study design
   *	Present and negotiate the project proposal at the Medical Ethical Committee panel
   * Participation in the writing of the grant proposals by providing sample size/power calculations and justification and description of the experiment design
   * Extract, manage, organise and tidy data into appropriate formats for analysis
   * Implement the planned data analysis to meet the project's objectives using `R` and other software packages for data analysis as required
   * Prepare and present formal written reports summarising and interpreting the study results using graphs and tables together with explanations of the statistical methods used

### RESEARCH

My research work has developed my knowledge and skills within the area of statistical modelling and statistical computing, which are now regarded as practical tools for researchers. As such, the area of my research enhances the opportunities for cross discipline research projects. 

A part of my PhD research focused on the study of a kernel smooth bootstrap method for assessing the accuracy of a quantile parametric regression function estimate, based on estimation of the conditional variance function. The study examines a variety of approaches to estimate the conditional variance function. These include the adaptation of GLMs as well as non-parametric regression based estimation, which are assessed under various data structures simulated in *R*, a public domain language for data analysis.

To validate the proposed bootstrap method I have carried out extensive simulation studies. The performance of the proposed method has also been compared with many other existing methods, which requires substantial statistical knowledge and high level computational skills.

Apart from statistical modelling, my interests are also in the area of statistical computing and data visualisations, which can make exploring data feel more compelling. Interactive visualisation can be an effective way of engaging an audience who might not otherwise care about the topic or data at hand.

In general, I find joy in analysing complex data sets to create clear and compelling reports, visualisations, and interactive apps. I love to write educational materials to develop data literacy.

### RESEARCH GRANTS and AWARDS

- Research Fund, UCLan, 2016$;$ to be spent on research related activities that can make a difference to a research project or grant application
- College Project Fund, 2015$;$ to provide leverage within schools to develop innovative projects and to progress ideas and to unlock potential for which funding is proving to be a barrier; Project: "Data Science Initiative"
- Homoeopathic Pharmacy UK and NHS funding, 2014$;$ to assist research into rheumatism and arthritis; Project: "Assessment of clinical effectiveness of adjunctive homoeopathic treatment for patients with Rheumatoid Arthritis"
- Livesey Research Awards, UCLan, 2009$;$ 6 months sabbatical leave and research funding
- King Abdul Aziz City for Science and Technology, 2006: KACST fund$;$ Constructing Growth Charts for Saudi Arabian Children and Adolescents

### TOOLS AND SKILLS

- Quantitative research and statistical modelling:
    + Inquisitive about finding insight in data
    + Experienced in working with large datasets and using advanced data analysis to answer complex questions.
    + Proficient in mastering new knowledge and techniques quickly and able to understand and articulate what questions can and cannot be answered given certain data 
    + Experienced in using statistical modelling techniques. In particular, familiar with machine learning, including supervised and unsupervised learning techniques, and how to build predictive models

- Writing and speaking for target and general audiences

### COMMUNITY INITIATIVES

- [**WiDS Subotica Conference 2020**](https://suwids2.netlify.app) is an initiative that aims to inspire and educate data scientists worldwide, regardless of gender, and support women in the field
- **DS Serbia Caravan**: promoting the R-Ladies initiative and introducing current chapters BG and NS as a part of the wider DS community within Serbia, December 2019
- **I’mpowered for the future** ambassador: an initiative that aims to empower young women with programming knowledge and rais an awareness of a wide array of jobs that require basic programming skills; November 2019
- **Women in IT and Entrepreneurship**: moderator of the panel discussion; Startit, Novi Sad, Serbia, 29 August 2019
- [**RBootcamp**](http://rbootcamp.rbind.io) is a platform built to provide an insightful overview on the data democracy process through the use of free open source data analysis software packages
- [**WiDS Subotica Conference 2019**](https://widssubotica.netlify.com) is an initiative that aims to inspire and educate data scientists worldwide, regardless of gender, and support women in the field
- **Future Directions of R**: Forum member as industrial representative at *Northwest Universities R Day*; Manchester, UK, 31 October 2018 
- [**klikR**](http://klikr.rbind.io) is an initiative designed to introduce and make accessible the art world of data science with the focus on the younger generation, existing students and those wishing to change the course of their career. It fosters greater inclusivity and gender diversity
- **Importance of IT communities**: Forum member as a coorganiser of R-Ladies chapters, moderated by Kejtlin Gilum from Meetup HQ NY; Startit, Belgrade, Serbia, 19 June 2018
- **N1 TV's Net Context: Data Science**; Belgrade, Serbia, 10 April 2018
- **R-Ladies Manchester, Belgrade and Novi Sad**, *Founder* and *coorganiser*: R-Ladies Manchester/Belgrade/Montenegro/Novi Sad are part of a global initiative, R-Ladies Global, designed to improve the gender diversity of R users worldwide and in particular, to improve the participation and experience of women in the R community
As part of the initiative, R-Ladies Manchester hosts talks and workshops about the use of R
- **Data Science Initiative for The College of Business, Law and Social Sciences at UCLan**, *Founder*:
The DS Initiative aims to raise the profile of learning, teaching and application of statistics appropriate for the analysis of social and economic datasets within the college

### PUBLICATIONS

A. Derbyshire, T. Kecojevic. *The Boka Kotorsk: A Vernacular Response to Sustainable Urban Environments.* Journal of Architecture and Urbanism, 2014; **38(2)**:148--160.

A. Derbyshire, T. Kecojevic. *The Evolution of the Boka Kotorska as a Sustainable Ecological Entity.* In: Proceedings IFKAD-KCWS 2012 - Knowledge, Innovation and Sustainability: integrating micro and macro perspectives. IFKAD-KCWS, Matera, Italy, 2012; pp. 1438--1458. ISBN 978--88-96687--08--6. 

M.I. El Mouzan, A.S. Al Herbish, A. A. Al Salloum, P.J. Foster, A.A. Al Omar; M.M. Qurachi, T. Kecojevic. *Regional disparity in prevalence of malnutrition in Saudi children*, Saudi Medical Journal. 2010; **31(5)**:550--554.

P.J. Foster, T. Kecojevic. *Construction of the Reference Growth Charts for Saudi Arabian Children and Adolescents*, Advances in Social Science Research Using R; Series: Lecture Notes in Statistics; Subseries: Lecture Notes in Statistics - Proceedings; Springer-Verlag, New York 2010. **196**:107--128.

M.I. El Mouzan, A.S. Al Herbish, A. A. Al Salloum, P.J. Foster, A.A. Al Omar; M.M. Qurachi, T. Kecojevic. *Pattern of Sex Differences in Growth of Saudi Children and Adolescents*, Gender Medicine 2010; **7(1)**:47--54.

Mohammad I. El Mouzan, Peter J. Foster, Abdullah S. Al Herbish, Abdullah A. Al Salloum, Ahmad A. Al Omar, Mansour M. Qurachi, Tatjana Kecojevic. *Prevalence of overweight in preschool children using the new WHO growth standards*, e-SPEN, The European e-Journal of Clinical Nutrition and Metabolism 2010; **5(1)**:10--13.

M.I. El Mouzan, P.J. Foster, A.S. Al Herbish, A.A. Al Salloum, A.A. Al Omar, M.M. Qurachi, T. Kecojevic. *The Implications of Using the World Health Organization Child Growth Standards in Saudi Arabia*, Nutrition Today 2009;  **44(2)**:62--70.

M.I. El Mouzan, P. Foster, A. Al Herbish, A. Al Salloum, A. Al Omar, M. Alqurshi, T. Kecojevic. *Regional variations in the growth of Saudi children and adolescents*, Annals of Saudi Medicine 2009; **29(5)**:348--356.

A.S. Al Herbish, M.I. El Mouzan, A.A. Al Salloum, M.M. Al Qureshi, A.A. Al Omar, P.J. Foster, T. Kecojevic. *Body mass index in Saudi Arabian children and adolescents: A national reference and comparison with international standards*, Annals of Saudi Medicine 2009; **29(5)**:342--347.

M.I. El Mouzan, A.S. Al Herbish, A.A. Al Salloum, A.A. Al Omar, M.M. Qurachi, P.J. Foster, T. Kecojevic. *Comparison of the 2005 Saudi with the 2000 CDC growth charts*, Annals of Saudi Medicine, 2008;  **28(5)**:334--340.

J.A. Ellison, L. Patel, T. Kecojevic, P.J. Foster, T.J. David, P.E. Clayton. *Pattern of growth and adiposity from infancy to adulthood in atopic dermatitis*, British Journal of Dermatology 2006; **155(3)**:532--538.

### CONFERENCE PRESENTATIONS

T. Kecojevic *Transparent Journalism Through the Power of R*, The European R Users Meeting, eRum 2020, Milan, Italy, 17-20 June 2020 

T. Kecojevic *Importance of R-Ladies Initiative in DS Community*, DSC 4.0, Data Science Conference 4.0, Belgrade, Serbia, 18-19 September 2018. 

T. Kecojevic *Setting up your R workshop in the cloud*, eRum 2018 Conference, European R Users Meeting; Budapest, Hungary, 14-16 May 2018.

T. Kecojevic, A.K. Derbyshire. *Data Landscapes: a pragmatic and philosophical visualisation of the  sustainable urban landscape*, useR!2016 Conference; The R User Conference 2016; Stanford University, Stanford, California, USA, 27-30 June 2016. 

T. Kecojevic, *Data Landscapes: a pragmatic and philosophical visualisation of the  sustainable urban landscape*, UCLan's Learning and Teaching Conference 2016, Preston, UK, 23-24 June 2016. 

T. Kecojevic, *Workshop: Developing Graphs in R*. UCLan's Learning and Teaching Conference 2016, Preston, UK, 23-24 June 2016. 

T. Kecojevic. *GLM - a case study: Antagonistic relationships between fungi and nematodes*, useR!2013 Conference; The R User Conference 2013; University of Castilla-La Mancha, Albacete, Spain, 10-12 July 2013 (accepted)

V. Oro, T. Kecojevic, S. Tosi. *Hatching inhibition of Globodera rostochiensis by some fungal isolates*, 31st International Symposium of the European Society of Nematologies; Adena, Turkey; 23-27 September 2012             

T. Kecojevic, P.J. Foster. *Smooth Bootstrap Inference for Parametric Quantile Regression*, Applied Statistics 2012 International Conference -- AS2012; Ribno, Bled, Slovenia, 23-26 September 2012

A.K. Derbyshire, T. Kecojevic. *The Evolution of the Boka Kotorska as a Sustainable Urban Ecological Entity*, IFKAD - KCWS 2012 joint conference; Knowledge, Innovation and Sustainability: Integrating Micro and Macro Perspectives, Matera-Italy, 13-15 June 2012 

T. Kecojevic, P.J. Foster. *Smooth Bootstrap Inference for Parametric Quantile Regression*, useR!2012 Conference; The 8th International R Users Meeting; Vanderbilt University, Nashville, Tennessee, USA, 12-15 June 2012

P.J. Foster, T. Kecojevic. *Construction of the Reference Growth Charts for Saudi Arabian Children and Adolescents*, Conference on Quantitative Social Science Research Using R, Fordham University, New York, USA, 18-19 June 2009

P.J. Foster, T. Kecojevic. *Inference in Quantile Regression via the Conditional Variance Function*, MANTAWORL09, Tamper School of Public Health, University of Tamper, Finland, 19--20 May 2009

T. Kecojevic. *Quantile Regression*, LBS Research Symposium, Preston, UK, 4 July 2008

T. Kecojevic. *Construction of the Reference Growth Charts for Saudi Arabia*, LBS Seminar, Preston, UK, 14 March 2008

T. Kecojevic. *Using LMS method for Reference Growth Charts*, LBS Research Symposium, Preston, UK, 21 Jun 2007

T. Kecojevic. *Using LMS method for Reference Growth Charts*, Mathematics Research Students' Conference -- MRSC2007, Manchester, UK, 9 May 2007

### WORKSHOPS DELIVERED

*[Introduction to R](https://introtor.netlify.app)*; ASDA, Leeds U.K., 18 November 2020

*[Build a website with blogdown in R](https://websiteinr.netlify.app)*; The European R Users Meeting, eRum 2020, Milan, Italy, 17-20 June 2020 

*[DS Bootcamp in R](http://dsbootcamp.rbind.io)*; InfoStud, Subotica, Serbia, 07-14 March 2020

*[Open Data Challenge](https://ohsa.netlify.app)*; Open Heroines, Belgrade, Serbia, 09 March 2020

*[R-Toolbox for Journalism](https://rtoolbox.netlify.com/en/)*; USAID Balkan Media Assistance Program (BMAP), Belgrade, Serbia, December 2019 - June 2020.

*[Reproducible Research in R](https://reproducibleresearchinr.rbind.io)*; University of Belgrade, Belgrade, Serbia; 12 November 2019 and Belgrade Open School, Belgrade, Serbia, 30 January 2020.

*[Responding to analysis and communication: Data science the R way](https://github.com/RLadiesBelgrade/DSC5_RWS/blob/master/DSRWay.html)*; DSC 5.0, Data Science Conference 5.0, Belgrade, Serbia, 17 November 2019 

*[Open Data Challenge](https://datachallengewithr.rbind.io)*; UNDP Serbia: The Autumn Data School, Mokrin, Serbia, 29-31 October 2019

*[RBootcam](http://rbootcamp.rbind.io/)*; UNDP Serbia: Open Data - Open Opportunities, Belgrade, Serbia, 14-16 May 2019

*Are you a blogger yet? Build your website using R, RStudio and blogdown package*; Women in Data Science Conference, Subotica, Serbia, 25 April 2019

*klikR: Development of skills for processing open data in R*; UNDP Serbia: Open Data - Open Opportunities, Novi Sad, Serbia, 07 April 2019

*Data Democracy - Power to the people*; UNDP Serbia: Open Data - Open Opportunities, Subotica, Serbia, 04 April 2019 

*Data Democracy: How to Shiny?*; R-Ladies Belgrade, Belgrade, Serbia, 03 April 2019

*Build your website using R, RStudio and blogdown package*; Northwest Universities R Day, Manchester, UK, 31 October 2018 
*Dynamic Documents with `R` Markdown*; R-Ladies Belgrade, Belgrade, Serbia, 20 June 2018

*Responding to analysis and communication: Data science the `R` way*; Enter Conference 2018, Belgrade, Serbia, 26 April 2018

*Building Shiny Apps and Playing with open data: Exploratory data analysis*; The First Open Data Week in Serbia, Belgrade, Serbia, 11 March 2018

*Data Wrangling and Visualisation*; R-Ladies Belgrade, Belgrade, Serbia, 13 February 2018 

*Why `R`?* An illustration through the use of `ggplota` and `magic`; R-Ladies Belgrade, Belgrade, Serbia, 20 December 2017

*Tidy your `R`!*; R-Ladies Manchester, Manchester, UK, 17 October 2017

*Tools we use in a Data Science project*; R-Ladies Manchester, Manchester, UK, 26 September 2017

*`blogdown`: Creating Websites with `R` Markdown*; R-Ladies Manchester, Manchester, UK, 05 July 2017

*Developing Shiny Apps*; R-Ladies Manchester, Manchester, UK, 10 May 2017

*Fundamental Concepts of `R`*; R-Ladies Manchester, Manchester, UK, 14 December 2016 

*Developing Graphs in `R`* UCLan's Learning and Teaching Conference 2016, University of Central lancashire, Preston, UK, 24 June 2016

### POSTER PRESENTATIONS 

T. Kecojevic. *Shiny App: Bootstrap to Comprehend Statistical Significance*, Advances in Data Science; Data Science Institute of the University of Manchester, UK, 15-16 May 2017

### CONFERENCE MODERATION

Keynote moderator; keynote speaker Amelia McNamara *Speaking R*, useR!2020 Conference; The 16th International R Users Meeting; St. Louis, USA and Munich, Germany, 09 July 2020  

Programme moderator; WiDS Subotica Conference 2019, Serbia, 25 April 2019  

### CONFERENCE PARTICIPATION

useR!2020 Conference; The 16th International R Users Meeting; St. Louis, USA and Munich, Germany, July 2020

eRum 2020 Conference; The European R Users Meeting, Milan, Italy, 17-20 June 2020 

WiDS Subotica Conference 2020, Serbia, 29 April 2020 

DSC 5.0, Data Science Conference 5.0, Belgrade, Serbia, 18-20 November 2019 

WiDS Subotica Conference 2019, Serbia, 25 April 2019 

DSC 4.0, Data Science Conference 4.0, Belgrade, Serbia, 18-19 September 2018 

eRum 2018 Conference; The European R Users Meeting, Budapest, Hungary, 14-16 May 2018 

Enter Conference 2018; Belgrade, Serbia, 25-26 April 2018

Advances in Data Science; Data Science Institute of the University of Manchester, UK; 15-16 May 2017

useR!2016 Conference; The 12th International R Users Meeting; Stanford University, Stanford, California, USA, 27-30 June 2016

UCLan's Learning and Teaching Conference 2016, Preston, UK, 23-24 June 2016

Applied Statistics 2012 International Conference -- AS2012; Ribno, Bled, Slovenia, 23-26 September 2012

useR!2012 Conference; The 8th International R Users Meeting; Vanderbilt University, Nashville, Tennessee, USA, 12-15 June 2012

Conference on Quantitative Social Science Research Using R, Fordham University, New York, USA, 18-19 June 2009

Cemmap, ESRC Econometric Study Group, Workshop on Quantile Regression, London, UK; 1-2 June, 2009

LBS Research Symposium, Preston, UK, 4 July 2008

LBS Seminar, Preston, UK, 14 March 2008

useR!2007 Conference, Iowa State University, Aims, Iowa, USA;  8-10 August, 2007  

LBS Research Symposium, Preston, UK, 21 Jun 2007

Mathematics Research Students' Conference -- MRSC2007, Manchester, UK, 9 May 2007

### WORKSHOP PARTICIPATION 

Efficient `R` Programming by Colin Gillespie -- Jumping Rivers; eRum 2018 Conference; European R Users Meeting, Budapest, Hungary, 14 May 2018.

Building a package that lasts by Colin Fay; eRum 2018 Conference; European R Users Meeting, Budapest, Hungary, 14 May 2018.

Dynamic Documents with R Markdown by Yihui Xie -- RStudio, Inc; useR!2016 Conference; The 12th International R Users Meeting; Stanford University, Stanford, California, USA, 27 June 2016. 

Understanding and Creating Interactive Graphics by Toby Dylan Hocking -- McGill and Claus Thorn Ekstrom -- University of Copenhagen; useR!2016 Conference; The 12th International R Users Meeting; Stanford University, Stanford, California, USA, 27 June 2016.

Creating effective visualisations by Hadley Wickham -- RStudio; AS2012; Ribno, Bled, Slovenia, 26 September 2012.

Cloud Computing for the R environment by Karim Chine; useR!2012 Conference; The 8th International R Users Meeting; Vanderbilt University, Nashville, Tennessee, USA, 12 June 2012.

Regression Modelling Strategies by Frank E Harrell Jr; useR!2007 Conference; Iowa State University, Ames, Iowa, USA, 08 August 2007.

### PROFESSIONAL AFFILIATIONS

The Higher Education Academy
